###
HEAD https://localhost:7068/api/v1/AccountSpecs

###
POST https://localhost:7068/api/v1/AccountSpecs
Content-Type: application/json

{
  "name": "string1",
  "group": "string",
  "description": "string"
}
